name: testweb.grassi.dk
favicon: null
layout_spectrum: 0.9881032553967088
typography_spectrum: 0.4784850259311497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08321766927838326
  lightness: 0.33901434834115207
  saturation: 0.2743342181202024
  rhythmicContrast: 0.1281184300314635
purpose: []
